### ISSUE TITLE
bash: line 2: ./scripts/metadata.pl: Permission denied

### ISSUE THREAD

**Issue by goxofy** [haohaolee/shadowsocks-openwrt#1]
你好，brcm63xx平台编译不成功，似乎是权限问题，但不知如何解决？

Collecting package info: done
Collecting target info: done
bash: line 2: ./scripts/metadata.pl: Permission denied
Failed to build tmp/.config-package.in
bash: ./scripts/metadata.pl: Permission denied
make[1]: **\* [prepare-tmpinfo] Error 1
make: **\* [package/shadowsocks-openwrt/libev/install] 错误 2

求教！

**Comment by haohaolee** [comment]
权限问题似乎和源码无关，试试用 root 来 build。请问你编译的平台，另外如果从源码 build OpenWrt 本身可以成功吗

**Comment by goxofy** [comment]
我试过以root权限编译，还是这个问题，环境是ubuntu 12.04,我是从downloads.openwrt.org下载的brcm63xx的sdk，然后进入目录clone下git编译的。。

**Comment by haohaolee** [comment]
那在 make 最后加上一个 V=99 看看具体错在哪里，另外你下载的是哪一版的 SDK

**Comment by goxofy** [comment]
我试试看看~  

下载的是这个sdk  http://downloads.openwrt.org/backfire/10.03.1/brcm63xx/OpenWrt-SDK-brcm63xx-for-Linux-i686-gcc-4.3.3%2bcs_uClibc-0.9.30.1.tar.bz2

**Comment by goxofy** [comment]
ubuntu是64bit的

**Comment by goxofy** [comment]
加了V=99之后，错误提示完全相同。。。

**Comment by haohaolee** [comment]
试试这个呢 http://downloads.openwrt.org/attitude_adjustment/12.09-rc1/brcm63xx/generic/OpenWrt-SDK-brcm63xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2.tar.bz2
我怀疑还是和发行版有关。不行，我晚上再看看

**Comment by goxofy** [comment]
我试下，谢谢！
