### ISSUE TITLE
求直接编译好BCM平台的

### ISSUE THREAD

**Issue by trawor** [haohaolee/shadowsocks-openwrt#2]

**Comment by haohaolee** [comment]
http://www.v2ex.com/t/56298#reply60 看回帖

**Comment by haohaolee** [comment]
不过我疏忽了，你说的是BCM哪个平台的，BCM有几个呢

**Comment by trawor** [comment]
这是硬件信息  我不太懂这个是什么平台...

Model   Linksys E3200 v1.0
Chipset Broadcom BCM5357 chip rev 1 pkg 10
CPU Freq    500MHz
Flash Size  16MB

**Comment by haohaolee** [comment]
噢，那是BCM47xx，你可以试试这个 http://downloads.openwrt.org/attitude_adjustment/12.09-rc1/brcm47xx/generic/OpenWrt-SDK-brcm47xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2.tar.bz2
可以运行在x86的linux上，应该很容易build的
如果实在不方便自己build，那我抽时间下载做一个

**Comment by yuanji-dev** [comment]
请问有brcm63XX平台编译好的么 昨晚编译好久都没成功。。。

**Comment by haohaolee** [comment]
可以看看这里： http://shadowsocks.org/downloads

**Comment by yuanji-dev** [comment]
上边貌似只有brcm47XX 的，没有brcm63XX的

**Comment by haohaolee** [comment]
不好意思，那稍等一下吧。我需要下载SDK来build一个

**Comment by trawor** [comment]
请加上我这个吧

Model
Linksys E3200 v1.0

Chipset
Broadcom BCM5357 chip rev 1 pkg 10

CPU Freq
500MHz

Flash Size
16MB

## 

Travis
@trawor

在 2013年4月7日星期日，下午2:56，haohaolee 写道：

> 不好意思，那稍等一下吧。我需要下载SDK来build一个  
>

**Comment by haohaolee** [comment]
http://shadowsocks.org/downloads 上面就有 47xx 的，E3200 V1就是 bcm47xx 的

**Comment by trawor** [comment]
但是我安装的时候 报错

# ipkg install shadowsocks-libev_1.0-f3a138c378508c0acf54a88f1f8be1666c2e1f08_brcm47xx.ipk

Clearing state_want and state_flag for pkg=shadowsocks-libev (arch_priority=0 flag=16 want=2)
Nothing to be done
An error ocurred, return value: 4.
Collected errors:
Cannot find package shadowsocks-libev.
Check the spelling or perhaps run 'ipkg update'

## 

Travis
@trawor

在 2013年4月7日星期日，下午3:12，haohaolee 写道：

> http://shadowsocks.org/downloads 上面就有 47xx 的，E3200 V1就是 bcm47xx 的  
>

**Comment by haohaolee** [comment]
似乎你下载的是新版的，我得和那个package的maintainer沟通一下看看。我这边很久没更新了

**Comment by haohaolee** [comment]
有个奇怪的地方，为什么你的命令行是 ipkg install ？
你看看你装的 OpenWrt 是哪一版的，这个 ipk 恐怕不支持 DDWrt 之类的固件

**Comment by trawor** [comment]
我是番茄固件...

## 

Travis
@trawor

在 2013年4月7日星期日，下午6:08，haohaolee 写道：

> 有个奇怪的地方，为什么你的命令行是 ipkg install ？  
> 你看看你装的 OpenWrt 是哪一版的，这个 ipk 恐怕不支持 DDWrt 之类的固件  
>

**Comment by haohaolee** [comment]
那你恐怕只能从源码入手了，看看 Tomato 有没有 SDK

**Comment by trawor** [comment]
我是搞iOS 对这个平台 完全不懂

**Comment by haohaolee** [comment]
请问你的固件是在哪里下载的

**Comment by trawor** [comment]
我的固件是这个 http://tomato.groov.pl/download/K26RT-N/build5x-108-PL/Linksys%20E-series/tomato-E3200USB-NVRAM60K-1.28.RT-N5x-MIPSR2-108-PL-AIO.bin

源码在这儿  http://repo.or.cz/w/tomato.git/tree/refs/heads/tomato-shibby-RT-N  

## 

Travis
@trawor

在 2013年4月7日星期日，下午6:27，haohaolee 写道：

> 请问你的固件是在哪里下载的  
>

**Comment by haohaolee** [comment]
看起来挺麻烦的。不过在此之前你可以试试把之前那个ipk解压了，看看二进制文件能否直接运行。可以的话也可以凑合着用

**Comment by trawor** [comment]
竟然能跑起来 说明CPU支持 没问题  但还是报错:

 2013-04-07 23:49:28 INFO: calculating ciphers...
 2013-04-07 23:49:30 INFO: server listening at port 1081.
 ss-local: can't resolve symbol 'epoll_create1' in lib 'ss-local'.

根这儿说的一样
http://www.v2ex.com/member/shural/replies

**Comment by haohaolee** [comment]
真是头大呢，这说明kernel或者libc没有导出这个符号。如果可能的吧，能不能把libc.so发给我看看

**Comment by haohaolee** [comment]
@Gimo
http://buildbot.sinaapp.com/ 已经有bcm63xx的啦 你可以测试

**Comment by haohaolee** [comment]
@Travis 试试这个 http://pan.baidu.com/share/link?shareid=417591&uk=4009856320
还是解压了测试

**Comment by trawor** [comment]
这个可以跑起来了  没有报错 (用配置文件会报错 直接加参数的可以)

但真正访问网络的时候  服务端报错(python版本):

Traceback (most recent call last):
  File "/usr/lib/python2.6/SocketServer.py", line 558, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.6/SocketServer.py", line 320, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.6/SocketServer.py", line 615, in **init**
    self.handle()
  File "server.py", line 105, in handle
    addrtype = ord(self.decrypt(sock.recv(1)))
TypeError: ord() expected a character, but string of length 0 found

是需要我在客户端的参数里面设定method?  

## 

Travis
@trawor

在 2013年4月8日星期一，下午6:12，haohaolee 写道：

> @Travis 试试这个 http://pan.baidu.com/share/link?shareid=417591&uk=4009856320  
> 还是解压了测试  
>

**Comment by haohaolee** [comment]
不好说，也有可能就是客户端的问题。毕竟这是我用OpenWrt的SDK编出来的，有可能不兼容呢。你把各种参数都加上试试

**Comment by trawor** [comment]
-m 的两个参数都试过 服务器都会报同样的错  用rc4做参数的时候 本地报错:

ERROR: remote recv: Connection reset by peer on File: utils.c Line: 21  

## 

Travis
@trawor

在 2013年4月8日星期一，下午7:29，haohaolee 写道：

> 不好说，也有可能就是客户端的问题。毕竟这是我用OpenWrt的SDK编出来的，有可能不兼容呢。你把各种参数都加上试试  
>

**Comment by haohaolee** [comment]
嗯，那还是得用tomato自己的source来build。我研究研究吧，要花些时间

**Comment by yuanji-dev** [comment]
@haohaolee 谢谢，我试试咯

**Comment by haohaolee** [comment]
@Travis http://pan.baidu.com/share/link?shareid=417924&uk=4009856320
再弄不好我也没辙了，我个人是没有tomato的，所以没法测试和调试

2013/4/8 haohao lee hayatelee@gmail.com

> 嗯，那还是得用tomato自己的source来build。我研究研究吧，要花些时间
>

**Comment by trawor** [comment]
好兄弟! 成了!  可以用了!!

## 

Travis
@trawor

在 2013年4月8日星期一，下午10:44，haohaolee 写道：

> @Travis http://pan.baidu.com/share/link?shareid=417924&uk=4009856320  
> 再弄不好我也没辙了，我个人是没有tomato的，所以没法测试和调试  
> 
> 2013/4/8 haohao lee <hayatelee@gmail.com (mailto:hayatelee@gmail.com)>  
> 
> > 嗯，那还是得用tomato自己的source来build。我研究研究吧，要花些时间  
> >

**Comment by haohaolee** [comment]
那就好~

**Comment by haohaolee** [comment]
你需要用10.03-RC6的SDK来build，build过程在Readme里面有写
