### ISSUE TITLE
申请设备支持

### ISSUE THREAD

**Issue by wen-long** [haohaolee/shadowsocks-openwrt#7]
路由器型号 ASUS RT-N13
CPU型号   Ralink RT3052 id:1 rev:3
据说“I can request for more device support by posting issues on GitHub.”
所以就发了
这方面本人完全不懂，如果能做的话就太感谢了

**Comment by haohaolee** [comment]
这个我现在已经没有维护了，后续的更新你可以到这里找，http://www.shadowsocks.org/downloads ，现在还没有 Ralink 平台的，你可以试着先联系现在的维护者 madeye，让他支持。

**Comment by wen-long** [comment]
奥，谢谢了
另外那个网站OpenWRT条目有错误，点击`Source: GitHub`打开的是不存在页面，打开`Maintained by @madeye`却是你的。。。
